//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLiCuaHangTapHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KienThuc
    {
        public int MaKT { get; set; }
        public string TieuDe { get; set; }
        public string MoTaNgan { get; set; }
        public string NoiDung { get; set; }
        public string ChuDeChinh { get; set; }
        public string AnhDaiDien { get; set; }
        public string Slug { get; set; }
        public Nullable<int> MaDM { get; set; }
        public Nullable<int> MaSP { get; set; }
        public string TacGia { get; set; }
        public string NguonThamKhao { get; set; }
        public bool TrangThai { get; set; }
        public int LuotXem { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
