//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLiCuaHangTapHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuXemThongBao
    {
        public int Id { get; set; }
        public int MaThongBao { get; set; }
        public int MaKH { get; set; }
        public System.DateTime NgayXem { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual ThongBao ThongBao { get; set; }
    }
}
