//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLiCuaHangTapHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuThongBao
    {
        public int Id { get; set; }
        public int BaoNoId { get; set; }
        public string Loai { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayGui { get; set; }
    
        public virtual BaoNo BaoNo { get; set; }
    }
}
