//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLiCuaHangTapHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhuongThucThanhToan
    {
        public int MaPTTT { get; set; }
        public int MaHD { get; set; }
        public string MaLoaiThanhToan { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual LoaiThanhToan LoaiThanhToan { get; set; }
    }
}
