//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLiCuaHangTapHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongBao()
        {
            this.LichSuXemThongBao = new HashSet<LichSuXemThongBao>();
        }
    
        public int MaThongBao { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public string Loai { get; set; }
        public string DoiTuong { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string TrangThai { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public string Link { get; set; }
        public string Icon { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuXemThongBao> LichSuXemThongBao { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
