//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLiCuaHangTapHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuChi
    {
        public int MaTC { get; set; }
        public System.DateTime Ngay { get; set; }
        public string Loai { get; set; }
        public int SoTien { get; set; }
        public string DienGiai { get; set; }
    }
}
