//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLiCuaHangTapHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinNhan
    {
        public int MaTinNhan { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string SoDT { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public string TrangThai { get; set; }
        public System.DateTime NgayGui { get; set; }
        public Nullable<System.DateTime> NgayDoc { get; set; }
        public Nullable<int> NguoiPhanHoi { get; set; }
        public string NoiDungPhanHoi { get; set; }
        public Nullable<System.DateTime> NgayPhanHoi { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
